### ISSUE TITLE
Possible internationalization?

### ISSUE THREAD

**Issue by oskar-j** [pinceladasdaweb/Simple-PHP-Contact-Form#10]
Hi,

I wonder if it's possible to make the script responsive to browser's language setting?
Because I'm not particularly a PHP programmer, I would like to now:
- If such pull request would be welcome from my side whenever properly implemented,
- Is it difficult and where to start? It would be also good to change the input's "placeholder" arg as shown below because some browsers (i.e. Mozilla) show them

![in18](https://dl.dropboxusercontent.com/u/103068909/simple_form_in18.png)

**Comment by pinceladasdaweb** [comment]
Check this link: https://github.com/pinceladasdaweb/Simple-PHP-Contact-Form#how-to-use
