### ISSUE TITLE
Captcha ?

### ISSUE THREAD

**Issue by stuaxo** [pinceladasdaweb/Simple-PHP-Contact-Form#13]
Since contact forms

It would be great if this could support captcha, maybe by adding secureimage   https://www.phpcaptcha.org/

**Comment by pinceladasdaweb** [comment]
CAPTCHAs are [inaccessible](http://www.sitepoint.com/captcha-inaccessible-to-everyone/), but if you prefer, you can use [Google](https://github.com/google/recaptcha). Just follow the guide of how to implement.
