### ISSUE TITLE
Email validation problem : cannot use hyphen in domain name

### ISSUE THREAD

**Issue by asp111** [pinceladasdaweb/Simple-PHP-Contact-Form#15]
Hi,

can you please correct the regular expression to validate email's at contact-form.js

Currently, i cannot use hyphen in my email address at domain side.

ex: name@domain-one.com

If you change that to working email validation then this is quite good form.

Thanks,
Ashish

**Comment by asp111** [comment]
Thanks, its working properly now.

**Comment by ricardobelfort** [comment]
Estou com problemas pra enviar, utilizo servidor de hospedam locaweb versão windows estou usando o código do coleba Pedro, inclui tudo certinho, mas quando clica pra enviar e ele executa ação, ele volta com a msg de "enviado com sucesso", mas não consigo receber nada em meu e-mail.

Alguem poderia ajudar??
