### ISSUE TITLE
Recebimento

### ISSUE THREAD

**Issue by marquinhusgoncalves** [pinceladasdaweb/Simple-PHP-Contact-Form#16]
Implementei o Contact Form em meu site e fazendo os testes de envio da minha máquina em todos os navegadores o e-mail chega perfeitamente, porém se eu peço para qualquer outra pessoa enviar um contato o e-mail não chega, será que é algum bug ou erro de implementação em meu site?
Todo o código esta em https://github.com/marquinhusgoncalves/site-stephannieprint

**Comment by pinceladasdaweb** [comment]
Por que charset iso-8859-1ao invés de utf-8? Não vai quebrar caracteres com acentuação? Chegou a testar isso?

**Comment by marquinhusgoncalves** [comment]
Esqueci de mudar para utf-8, mas fiz os testes nos 2 funcionou perfeitamente....

**Comment by pinceladasdaweb** [comment]
Por favor, altere e submeta o pull request novamente. Obrigado.

**Comment by marquinhusgoncalves** [comment]
Imagina eu que agradeço.

**Comment by pinceladasdaweb** [comment]
Merged #17
