### ISSUE TITLE
Error return

### ISSUE THREAD

**Issue by Loic57** [pinceladasdaweb/Simple-PHP-Contact-Form#24]
Hey, 

I tried your code on localhost and it works good, but when i put it online i have an error

Parse error: syntax error, unexpected '[' in /home/loicscia/www/config/config.php on line 4

Can you help me please ?

**Comment by pinceladasdaweb** [comment]
Hi @Loic57,

Please paste the content of your config file here, please.

**Comment by Loic57** [comment]
this is your code, i changed nothing

`return [
    'subject' => [
        'prefix' => '[Contact Form]'
    ],
    'emails' => [
        'to'   => '',
        'from' => ''
    ],
    'messages' => [
        'error'   => 'There was an error sending, please try again later.',
        'success' => 'Your message has been sent successfully.'
    ],
    'fields' => [
        'name'     => 'Name',
        'email'    => 'Email',
        'phone'    => 'Phone',
        'subject'  => 'Subject',
        'message'  => 'Message',
        'btn-send' => 'Send'
    ]
];`

**Comment by thecotne** [comment]
Problem is in short array syntax if you write arrays with array keyword it will work (or you can install newer php on the server)

**Comment by ferrellw** [comment]
Updated to PHP Version 7.0.14 and above issue went away.

**Comment by Loic57** [comment]
It works, thank you
