### ISSUE TITLE
PHP Parse Error

### ISSUE THREAD

**Issue by henry7720** [pinceladasdaweb/Simple-PHP-Contact-Form#26]
**Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /home/a3416167/public_html/contact-form/index.php on line 10**
The code on line ten is 
`use Helpers\Config;
use SimpleMail\SimpleMail;`
Why is this arising?

**Comment by pinceladasdaweb** [comment]
What version of your PHP? The minimum version for this form to function is 5.4.
