### ISSUE TITLE
All messages go to spam...

### ISSUE THREAD

**Issue by henry7720** [pinceladasdaweb/Simple-PHP-Contact-Form#28]
Is there an issue? This form otherwise works wonderfully! here is my config:

<?php

return [
    'subject' => [
        'prefix' => '[Contact Form]'
    ],
    'emails' => [
        'to'   => 'example@example.com',
        'from' => ''
    ],
    'messages' => [
        'error'   => 'There was an error sending, please try again later.',
        'success' => 'Your message has been sent successfully.'
    ],
    'fields' => [
        'name'     => 'Name',
        'email'    => 'Email',
        'phone'    => 'Phone',
        'subject'  => 'Subject',
        'message'  => 'Message',
        'btn-send' => 'Send'
    ]
];

**Comment by pinceladasdaweb** [comment]
Hello @henry7720,

In the 'from' field add an email with the same domain where the form is hosted. This prevents emails from falling into SPAM.
