### ISSUE TITLE
How do you extract the html from index.php? 

### ISSUE THREAD

**Issue by Tzikas** [pinceladasdaweb/Simple-PHP-Contact-Form#29]
Write now the html form element is inside an index.php file.  Is there anyway to extract it to a plain index.html file and still have the contact form work?

**Comment by NazimAli2017** [comment]
Yes, just remove all the PHP from index.php and save as index.html.

**Comment by pinceladasdaweb** [comment]
Use Ajax version: https://github.com/pinceladasdaweb/Ajax-Contact-Form
