### ISSUE TITLE
'from' field set as form field value, sent with 'to' address twice

### ISSUE THREAD

**Issue by simonkilmore** [pinceladasdaweb/Simple-PHP-Contact-Form#30]
Hi, 

I have a strange issue. I've uploaded the project folder untouched except for entering the from and to in the config. In testing the form, the resulting email has two problems. Firstly, the 'from' address is not the address I set, on my domain, it's whatever I enter in the form. Secondly it's being sent to the 'to' address twice. The latter is not really too much of a problem but obviously the former is.

The to address is just my gmail. Sent with PHP 7.1.0

![firefox_2017-05-29_18-23-36](https://cloud.githubusercontent.com/assets/23053527/26557854/53324124-449c-11e7-922b-e2c0add3d53a.png)

steven@testy is obviously just fake data I entered into the form, but the same happens with a proper name/address.

**Comment by voloder** [comment]
Same problem.
Sent from PHP 5.4
Also it finishes in spam, both with real or fake address.
Page hosted on HostGator.

**Comment by brianjuhl** [comment]
Same issue here. Any one found a fix?

**Comment by pinceladasdaweb** [comment]
Fixed.
