### ISSUE TITLE
Send a confirmation email

### ISSUE THREAD

**Issue by Bawbd** [pinceladasdaweb/Simple-PHP-Contact-Form#33]
Hello,

I would like to send a confirmation email to the people that use the contact form to say thank you and that I'll contact them back asap.

How hard would it be to implement that?

Anyone can help me with that?

Thanks in advance for the help.

**Comment by eazylaykzy** [comment]
@Bawbd  you can use an autoresponder to achieve that, I believe it should come with your mail client, or your host provider.

If not, you can open a ticket with your host provider, and ask them how to go about it.
